name: "PyTest"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Set up virtual environment
        env:
          TERM: dumb
        run: |
          chmod +x python/Linux.sh
          ./python/Linux.sh

      - name: Run tests
        env:
          TERM: dumb
        run: |
          chmod +x PyTest/Linux.sh
          ./PyTest/Linux.sh